### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by marcinlukaszewski** [alesr/codetoprompt#3]
It would be nice to have the ability to copy the content of the repo directly to the clipboard. 
It seems that `https://github.com/golang-design/clipboard` could handle it for multiple platforms.

@alesr if you like, I could work on it (in case you haven't started already).

**Comment by alesr** [comment]
Good idea @mmllski!

How do you picture this implementation? By default copying the content to the user's clipboard?

**Comment by alesr** [comment]
btw @mmllski, feel free to work on it 💪🏼

**Comment by marcinlukaszewski** [comment]
> How do you picture this implementation? 

Not sure about the implementation.  From the user perspective, I can see two ways of handling this:
1. use  the`-out` flag with the following values:  ` clipboard | stdout | <filepath>`, 
2. change this flag's meaning to decide on output ` clipboard | stdout | file` and add an additional flag `-path` to specify a file path.

The first option has limitations, and the second requires an additional flag to specify the file path. If you have a preference or there is a better way, happy to look around 👀

> By default copying the content to the user's clipboard?

I'd use a clipboard as a default option as the user will paste the content into the chatgpt in a moment anyway, right? 😁

**Comment by alesr** [comment]
@mmllski excellent
